package quiz;
public class Questions {

    // Questions for OOP Java category (30 questions)
    public static final String[][] OOP_JAVA_QUESTIONS = {
        {"What does OOP stand for?", 
         "Object Oriented Programming", 
         "Operational Object Programming", 
         "Open Object Protocol", 
         "Object Open Protocol", 
         "Object Oriented Programming"},

        {"Which of these is a feature of OOP?", 
         "Inheritance", 
         "Polymorphism", 
         "Encapsulation", 
         "All of the above", 
         "All of the above"},

        {"What is inheritance in OOP?", 
         "A way to access private members", 
         "A mechanism to define a new class based on an existing class", 
         "A way to restrict class access", 
         "A way to implement multiple interfaces", 
         "A mechanism to define a new class based on an existing class"},

        {"What is polymorphism in OOP?", 
         "The ability to create multiple objects", 
         "The ability to perform different operations based on the object type", 
         "The ability to prevent class inheritance", 
         "The ability to hide data", 
         "The ability to perform different operations based on the object type"},

        {"What is encapsulation in OOP?", 
         "The ability to change the type of a class", 
         "The ability to restrict access to certain members of a class", 
         "The ability to inherit methods from other classes", 
         "The ability to create complex interfaces", 
         "The ability to restrict access to certain members of a class"},

        {"What is an abstract class?", 
         "A class with no constructor", 
         "A class that cannot be instantiated and can have abstract methods", 
         "A class that only has abstract methods", 
         "A class that can only be used in interfaces", 
         "A class that cannot be instantiated and can have abstract methods"},

        {"What is a constructor in Java?", 
         "A method to initialize objects", 
         "A method to finalize objects", 
         "A method to check conditions", 
         "A method to stop an object from being garbage collected", 
         "A method to initialize objects"},

        {"Which of the following is NOT a type of inheritance in Java?", 
         "Single Inheritance", 
         "Multiple Inheritance", 
         "Multilevel Inheritance", 
         "Hierarchical Inheritance", 
         "Multiple Inheritance"},

        {"What does the keyword 'super' refer to in Java?", 
         "The current class object", 
         "The parent class object", 
         "The private members of a class", 
         "The static members of a class", 
         "The parent class object"},

        {"What is method overloading in Java?", 
         "The ability to define multiple methods with the same name but different parameters", 
         "The ability to override a method", 
         "The ability to call a method in multiple classes", 
         "The ability to prevent method access", 
         "The ability to define multiple methods with the same name but different parameters"},

        {"Which of the following is used to create a subclass in Java?", 
         "extends", 
         "super", 
         "interface", 
         "implements", 
         "extends"},

        {"What is the main benefit of inheritance?", 
         "Reusability", 
         "Encapsulation", 
         "Polymorphism", 
         "Data hiding", 
         "Reusability"},

        {"What is the correct way to declare an interface in Java?", 
         "interface InterfaceName {}", 
         "class InterfaceName {}", 
         "abstract InterfaceName {}", 
         "enum InterfaceName {}", 
         "interface InterfaceName {}"},

        {"What is the difference between '==‘ and 'equals()' in Java?", 
         "'==' compares references, 'equals()' compares values", 
         "'==' compares values, 'equals()' compares references", 
         "'==' compares memory addresses", 
         "'equals()' compares memory addresses", 
         "'==' compares references, 'equals()' compares values"},

        {"Which access modifier allows access from within the same package?", 
         "public", 
         "private", 
         "protected", 
         "default", 
         "default"},

        {"Which of the following is NOT an advantage of OOP?", 
         "Increased code reusability", 
         "Improved debugging", 
         "Better organization of code", 
         "Increased complexity", 
         "Increased complexity"},

        {"What is the purpose of the 'final' keyword in Java?", 
         "To define a constant", 
         "To prevent method overriding", 
         "To prevent class inheritance", 
         "All of the above", 
         "All of the above"},

        {"Which of the following is the correct way to declare an abstract method?", 
         "abstract void methodName();", 
         "void abstract methodName();", 
         "methodName();", 
         "abstract void methodName;", 
         "abstract void methodName();"},

        {"What is method overriding in Java?", 
         "The ability to define a method in a subclass that already exists in the superclass", 
         "The ability to define multiple methods with the same name", 
         "The ability to hide a superclass method", 
         "The ability to modify a method’s signature", 
         "The ability to define a method in a subclass that already exists in the superclass"},

        {"What does the keyword 'this' refer to in Java?", 
         "The current class instance", 
         "The parent class instance", 
         "The current method", 
         "The static members of the class", 
         "The current class instance"},

        {"Which of the following keywords is used to inherit a class in Java?", 
         "extends", 
         "implements", 
         "super", 
         "interface", 
         "extends"},

        {"In which scenario would you use an abstract class?", 
         "When you want to provide a common base for subclasses", 
         "When you want to instantiate an object", 
         "When you need all methods to be implemented", 
         "When you want to create an interface", 
         "When you want to provide a common base for subclasses"},

        {"What is the purpose of the 'instanceof' operator?", 
         "To check the type of an object", 
         "To compare two objects", 
         "To cast objects", 
         "To check method accessibility", 
         "To check the type of an object"},

        {"Which of the following statements is true about the 'super' keyword?", 
         "'super' refers to the parent class", 
         "'super' is used to access the current class’s constructor", 
         "'super' is used to call a constructor in the subclass", 
         "'super' cannot be used in a constructor", 
         "'super' refers to the parent class"},

        {"Which of the following is true about interfaces in Java?", 
         "An interface can have abstract methods", 
         "An interface can have constructors", 
         "An interface can extend other interfaces", 
         "Both A and C", 
         "Both A and C"},

        {"What is the default value of a boolean variable?", 
         "false", 
         "true", 
         "0", 
         "null", 
         "false"},

        {"What is a package in Java?", 
         "A collection of classes and interfaces", 
         "A method for grouping related classes", 
         "A special type of variable", 
         "Both A and B", 
         "Both A and B"},

        {"What is the difference between 'final' and 'finally' in Java?", 
         "'final' is used to define constants or prevent method overriding, 'finally' is used for cleanup in exception handling", 
         "'final' is used for exception handling, 'finally' is used for constants", 
         "'final' is used to define classes, 'finally' is used to handle errors", 
         "'final' is used for memory management, 'finally' is used for handling exceptions", 
         "'final' is used to define constants or prevent method overriding, 'finally' is used for cleanup in exception handling"}
    };

    // Questions for Brain Testing category
    public static final String[][] BRAIN_TESTING_QUESTIONS = {
        {"A man pushes his car to a hotel and then tells the owner he’s bankrupt. What’s happening?", 
         "He lost money at hotel", 
         "He played Monopoly", 
         "His car broke down", 
         "He was fired", 
         "He played Monopoly"},

        {"What comes next in the series: 2, 6, 12, 20, 30, ?", 
         "36", 
         "38", 
         "42", 
         "44", 
         "42"},

        {"What number comes next? 121, 144, 169, 196, ?", 
         "221", 
         "225", 
         "250", 
         "200", 
         "225"},

        {"Which weighs more: a pound of bricks or a pound of feathers?", 
         "Bricks", 
         "Feathers", 
         "Equal", 
         "Depends on volume", 
         "Equal"},

        {"A farmer has 17 sheep, all but 9 run away. How many are left?", 
         "8", 
         "9", 
         "17", 
         "None", 
         "9"},

        {"If a bat and a ball cost $1.10 in total and the bat costs $1 more than the ball, how much is the ball?", 
         "5 cents", 
         "10 cents", 
         "15 cents", 
         "20 cents", 
         "5 cents"},

        {"How many times can you subtract 5 from 25?", 
         "5", 
         "1", 
         "25", 
         "Infinite", 
         "1"},

        {"Which number is odd one out: 2, 3, 5, 9, 11, 13", 
         "3", 
         "5", 
         "9", 
         "11", 
         "9"},

        {"Mary’s father has 5 daughters: Nana, Nene, Nini, Nono. Who is the fifth?", 
         "Nuna", 
         "Mary", 
         "Nunu", 
         "Nani", 
         "Mary"},

        {"If you’re running in a race and you pass the person in second place, what place are you in?", 
         "First", 
         "Second", 
         "Third", 
         "Fourth", 
         "Second"},

        // Other Brain Testing questions go here...

        {"What comes next in: 2, 3, 5, 7, 11, ?", 
         "12", 
         "13", 
         "15", 
         "17", 
         "13"},

        {"A clock shows 3:15. What’s the angle between hour and minute hand?", 
         "0°", 
         "7.5°", 
         "15°", 
         "30°", 
         "7.5°"},

        {"What 5-letter word becomes shorter when you add two letters to it?", 
         "Short", 
         "Shorter", 
         "Small", 
         "Shrink", 
         "Short"},

        {"If one brother says, “That’s my sister,” and the other says, “That’s my daughter,” what’s their relationship?", 
         "Brothers", 
         "Father and son", 
         "Cousins", 
         "Twins", 
         "Father and son"},

        {"In a family of six, each member shakes hands with every other once. How many handshakes?", 
         "12", 
         "15", 
         "20", 
         "30", 
         "15"},

        {"A man has 53 socks: 21 black, 15 blue, 17 red. Minimum to pull out a matching pair?", 
         "3", 
         "4", 
         "2", 
         "5", 
         "3"},

        {"Which number replaces the question mark? 9 + 1 = 91, 8 + 2 = 82, 7 + 3 = 73, 6 + 4 = ?", 
         "10", 
         "64", 
         "46", 
         "100", 
         "64"},

        {"Two fathers and two sons went fishing. They caught 3 fish. How can they divide it evenly?", 
         "Cut the fish", 
         "One person eats less", 
         "There are only 3 people", 
         "Impossible", 
         "There are only 3 people"},

        {"The more you take, the more you leave behind. What am I?", 
         "Footsteps", 
         "Air", 
         "Memory", 
         "Nothing", 
         "Footsteps"},

        {"A girl has as many brothers as sisters, but her brother has only half as many brothers as sisters. How many siblings are there?", 
         "4 girls, 3 boys", 
         "3 girls, 4 boys", 
         "2 girls, 2 boys", 
         "1 girl, 2 boys", 
         "4 girls, 3 boys"}
    };
}